/**
 * ReportFooter - Solver information and disclaimer
 */

import React from 'react';
import { SOLVER_VERSION } from '@/lib/solver';

interface ReportFooterProps {
  generatedAt?: string;
}

export function ReportFooter({ generatedAt }: ReportFooterProps) {
  const timestamp = generatedAt || new Date().toISOString();

  return (
    <footer className="mt-12 pt-6 border-t-2 border-gray-300">
      {/* Disclaimer */}
      <div className="mb-6 p-4 bg-yellow-50 border border-yellow-200 rounded-lg text-sm text-yellow-800">
        <h4 className="font-semibold mb-2">Important Disclaimer</h4>
        <p className="mb-2">
          This report is generated by an educational structural analysis tool. 
          The results are based on linear elastic analysis with the following assumptions:
        </p>
        <ul className="list-disc list-inside ml-4 space-y-1">
          <li>Material behaves linearly elastic (Hooke&apos;s Law)</li>
          <li>Small displacements (linear geometry)</li>
          <li>Euler-Bernoulli beam theory (no shear deformation)</li>
          <li>2D plane frame/truss analysis</li>
        </ul>
        <p className="mt-2 font-medium">
          This software is NOT intended for use in professional engineering practice. 
          All structural designs must be verified by a licensed professional engineer.
        </p>
      </div>

      {/* Technical Information */}
      <div className="grid grid-cols-2 gap-6 text-sm text-gray-600">
        <div>
          <h4 className="font-medium text-gray-800 mb-2">Solver Information</h4>
          <table className="w-full">
            <tbody>
              <tr>
                <td className="py-1">Version:</td>
                <td className="py-1 font-mono">{SOLVER_VERSION}</td>
              </tr>
              <tr>
                <td className="py-1">Method:</td>
                <td className="py-1">Direct Stiffness Method</td>
              </tr>
              <tr>
                <td className="py-1">Matrix Solver:</td>
                <td className="py-1">Cholesky / LU Decomposition</td>
              </tr>
              <tr>
                <td className="py-1">Element Types:</td>
                <td className="py-1">2-node Truss, 2-node Frame</td>
              </tr>
            </tbody>
          </table>
        </div>
        
        <div>
          <h4 className="font-medium text-gray-800 mb-2">Units System</h4>
          <table className="w-full">
            <tbody>
              <tr>
                <td className="py-1">Force:</td>
                <td className="py-1">kN (kilonewton)</td>
              </tr>
              <tr>
                <td className="py-1">Length:</td>
                <td className="py-1">m (meter)</td>
              </tr>
              <tr>
                <td className="py-1">Moment:</td>
                <td className="py-1">kN·m (kilonewton-meter)</td>
              </tr>
              <tr>
                <td className="py-1">Stress:</td>
                <td className="py-1">kPa (kilopascal)</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      {/* Generation timestamp */}
      <div className="mt-6 pt-4 border-t border-gray-200 flex justify-between items-center text-xs text-gray-500">
        <div>
          <p>Report generated: {new Date(timestamp).toLocaleString()}</p>
        </div>
        <div className="text-right">
          <p>Structural Analysis App</p>
          <p>© {new Date().getFullYear()} - Educational Use Only</p>
        </div>
      </div>

      {/* Page number placeholder (for print) */}
      <div className="mt-4 text-center text-xs text-gray-400 print:block hidden">
        Page <span className="page-number" />
      </div>
    </footer>
  );
}
